// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Hypnox Technologies LLC
//
//  GlyphLegend.swift
//  sublight-cli
//
//  Renders the menu bar icon's states FROM StatusGlyph, so the picture in the
//  README is generated by the same code that draws the live icon. A legend
//  drawn by hand is a legend that drifts: someone nudges a key rectangle, the
//  screenshot stays, and the documentation quietly starts lying. This is dev
//  tooling, which is why it lives with the CLI rather than shipping inside the
//  kit — the runtime glyph is still drawn in code, and no PNG is ever bundled
//  as an app resource.
//
//  DETERMINISM is a requirement, not a nicety: the output is committed, so a
//  re-render must produce identical bytes or every regeneration becomes a
//  spurious diff. Everything therefore draws into an explicit
//  NSBitmapImageRep with a fixed pixel size and a device RGB colour space —
//  never lockFocus(), which picks up whatever backing scale the current
//  display happens to have.
//
//  Licensed under the Apache License 2.0 — see LICENSE.
//

import AppKit
import Foundation
import SublightKit

enum GlyphLegend {

    struct State {
        let key: String
        let label: String
        let fraction: CGFloat
    }

    /// The four shipped states. Fractions match DimmingPolicy.glyphFraction.
    static let states: [State] = [
        State(key: "off",    label: "Off",         fraction: 0.0),
        State(key: "low",    label: "Low 3 Hz",    fraction: 0.3),
        State(key: "medium", label: "Medium 6 Hz", fraction: 0.5),
        State(key: "high",   label: "High 8 Hz",   fraction: 0.8),
    ]

    static let legendFileName = "sublight-menubar-states.png"

    // MARK: Deterministic bitmap

    private static func bitmap(width: Int, height: Int, scale: Int,
                               _ draw: () -> Void) -> NSBitmapImageRep? {
        guard let rep = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: width * scale, pixelsHigh: height * scale,
            bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
            colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0
        ) else { return nil }
        rep.size = NSSize(width: width, height: height)
        guard let ctx = NSGraphicsContext(bitmapImageRep: rep) else { return nil }
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = ctx
        ctx.imageInterpolation = .high
        draw()
        ctx.flushGraphics()
        NSGraphicsContext.restoreGraphicsState()
        return rep
    }

    /// Recolour the template glyph — black shapes on transparency — the way
    /// macOS tints it for a real menu bar.
    ///
    /// This MUST happen in its own transparent bitmap. A sourceAtop fill
    /// composites wherever the destination is already opaque, so doing it
    /// directly onto the legend's coloured row would paint the entire cell
    /// instead of just the glyph — which is exactly the solid rectangle the
    /// first version of this produced.
    private static func tinted(_ fraction: CGFloat, side: CGFloat,
                               tint: NSColor, scale: Int) -> NSImage? {
        guard let rep = bitmap(width: Int(side), height: Int(side), scale: scale, {
            let r = NSRect(x: 0, y: 0, width: side, height: side)
            StatusGlyph.image(litFraction: fraction).draw(in: r)
            tint.set()
            r.fill(using: .sourceAtop)
        }) else { return nil }
        let image = NSImage(size: NSSize(width: side, height: side))
        image.addRepresentation(rep)
        return image
    }

    private static func draw(_ text: String, centeredIn rect: NSRect, y: CGFloat,
                             size: CGFloat, weight: NSFont.Weight, color: NSColor) {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: NSFont.systemFont(ofSize: size, weight: weight),
            .foregroundColor: color,
        ]
        let s = NSAttributedString(string: text, attributes: attrs)
        let w = s.size().width
        s.draw(at: NSPoint(x: rect.midX - w / 2, y: y))
    }

    // MARK: One state, on its own

    static func stateData(fraction: CGFloat, scale: Int) -> Data? {
        bitmap(width: 18, height: 18, scale: scale) {
            StatusGlyph.image(litFraction: fraction)
                .draw(in: NSRect(x: 0, y: 0, width: 18, height: 18))
        }?.representation(using: .png, properties: [:])
    }

    // MARK: The composed legend

    private static let cellW: CGFloat = 132
    private static let glyphBox: CGFloat = 54
    private static let titleH: CGFloat = 34
    private static let rowH: CGFloat = 84
    private static let labelH: CGFloat = 30

    static func legendData(scale: Int = 2) -> Data? {
        let width = cellW * CGFloat(states.count)
        let height = titleH + rowH * 2 + labelH

        // Tint in isolation BEFORE the page context exists — see `tinted`.
        let onDark = states.map { tinted($0.fraction, side: glyphBox, tint: .white, scale: scale * 2) }
        let onLight = states.map { tinted($0.fraction, side: glyphBox, tint: .black, scale: scale * 2) }

        return bitmap(width: Int(width), height: Int(height), scale: scale) {
            let page = NSRect(x: 0, y: 0, width: width, height: height)
            NSColor.white.setFill()
            page.fill()

            // Origin is bottom-left, so lay out upward: labels, light row,
            // dark row, title.
            let labelsY: CGFloat = 0
            let lightY = labelH
            let darkY = labelH + rowH
            let titleY = labelH + rowH * 2

            NSColor(white: 0.13, alpha: 1).setFill()
            NSRect(x: 0, y: darkY, width: width, height: rowH).fill()
            NSColor(white: 0.94, alpha: 1).setFill()
            NSRect(x: 0, y: lightY, width: width, height: rowH).fill()

            for (i, state) in states.enumerated() {
                let cell = NSRect(x: CGFloat(i) * cellW, y: 0, width: cellW, height: height)
                let gx = cell.midX - glyphBox / 2
                onDark[i]?.draw(in: NSRect(x: gx, y: darkY + (rowH - glyphBox) / 2,
                                           width: glyphBox, height: glyphBox))
                onLight[i]?.draw(in: NSRect(x: gx, y: lightY + (rowH - glyphBox) / 2,
                                            width: glyphBox, height: glyphBox))

                let lit = StatusGlyph.litKeyCount(litFraction: state.fraction)
                draw(state.label, centeredIn: cell, y: labelsY + 15, size: 11.5,
                     weight: .semibold, color: NSColor(white: 0.15, alpha: 1))
                draw("\(lit) of \(StatusGlyph.keyCount) keys lit",
                     centeredIn: cell, y: labelsY + 3, size: 9,
                     weight: .regular, color: NSColor(white: 0.45, alpha: 1))
            }

            draw("Sublight menu bar icon — dark and light menu bars",
                 centeredIn: page, y: titleY + 11, size: 12.5,
                 weight: .medium, color: NSColor(white: 0.2, alpha: 1))
        }?.representation(using: .png, properties: [:])
    }

    // MARK: Entry point

    /// Writes every per-state PNG at 1x and 2x plus the composed legend.
    /// Only the legend is committed to the repo (see CONTRIBUTING).
    static func render(to dir: URL) throws -> [String] {
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        var written: [String] = []
        for state in states {
            for scale in [1, 2] {
                guard let data = stateData(fraction: state.fraction, scale: scale) else {
                    throw NSError(domain: "GlyphLegend", code: 1, userInfo: [
                        NSLocalizedDescriptionKey: "could not render state \(state.key)@\(scale)x",
                    ])
                }
                let name = "glyph-\(state.key)@\(scale)x.png"
                try data.write(to: dir.appendingPathComponent(name), options: .atomic)
                written.append(name)
            }
        }
        guard let legend = legendData() else {
            throw NSError(domain: "GlyphLegend", code: 2, userInfo: [
                NSLocalizedDescriptionKey: "could not render the legend",
            ])
        }
        try legend.write(to: dir.appendingPathComponent(legendFileName), options: .atomic)
        written.append(legendFileName)
        return written
    }
}
